# image: php:7.2-cli

# pipelines:
#   branches:
#     '{master}':
#       - step:
#           name: Fractal Build
#           image: atlassian/default-image:2
#           caches:
#             - node
#           script:
#             - npm install
#             - npm install -g gulp
#             - gulp
#             - gulp production
#             - apt-get update
#             - apt-get install -y zip
#             - zip -r application.zip .
#             - pipe: atlassian/aws-code-deploy:0.2.9
#               variables:
#                 AWS_ACCESS_KEY_ID: 'AKIAX3FU5UAQSFPXDSBO'
#                 AWS_SECRET_ACCESS_KEY: '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'
#                 AWS_DEFAULT_REGION: 'us-west-2'
#                 APPLICATION_NAME: deployment-components
#                 S3_BUCKET: deployment-ucla-components
#                 COMMAND: 'upload'
#                 ZIP_FILE: 'application.zip'
#                 DEPLOYMENT_GROUP: componentsDeploy
#             - pipe: atlassian/aws-code-deploy:0.2.9
#               variables:
#                 AWS_ACCESS_KEY_ID: 'AKIAX3FU5UAQSFPXDSBO'
#                 AWS_SECRET_ACCESS_KEY: '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'
#                 AWS_DEFAULT_REGION: 'us-west-2'
#                 APPLICATION_NAME: deployment-components
#                 DEPLOYMENT_GROUP: componentsDeploy
#                 S3_BUCKET: deployment-ucla-components
#                 COMMAND: 'deploy'
#                 WAIT: 'true'
#                 IGNORE_APPLICATION_STOP_FAILURES: 'true'
#                 FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
#
image: node:latest

pipelines:
  branches:
    feature/CL-6-semantic-versioning-research:
      - step:
          caches:
            - node
          script:
            # Get an oauth access token using the client credentials, parsing out the token with jq (json processor).
            # - apt-get update && apt-get install -y curl jq
            # - npm install -g gulp
            # - export BB_TOKEN=$(echo “x-token-auth:”)$(curl -s -X POST -u "${CLIENT_ID}:${CLIENT_SECRET}" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials -d scopes=”repository” | jq — raw-output ‘.access_token’)
            # # Configure git to use the oauth token. This well happen when setting env variable BB_TOKEN
            # - gulp production
            # - npx semantic-release --debug
            # # set current tag number -- this will be used to deploy to the correct S3 public folder
            - export currTag=$(git describe --tags --abbrev=0)
            - export currTag="${currTag//v}"
            - echo $currTag
            # deploy build + public folders to S3 -- public directory should be deployed to S3 directory corresponding to tag name
            # - pipe: atlassian/aws-s3-deploy:0.2.1
            #   variables:
            #     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            #     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            #     AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            #     S3_BUCKET: test-fractal/build
            #     LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/build
            # - pipe: atlassian/aws-s3-deploy:0.2.1
            #   variables:
            #     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            #     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            #     AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            #     S3_BUCKET: test-fractal/public/test
            #     LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/public
